### ISSUE TITLE
Display prorated time of shots

### ISSUE THREAD

**Issue by imjakedaniels** [imjakedaniels/raptors_animation#4]
I have the data to show prorated shot time – possibly represented as `Q1 12:03` below the shot clock.

**Comment by imjakedaniels** [comment]
Since the animation's current_frame is sequenced along the running score variable, I'll need to glue the time_remaining onto the running score. It will also need to be in the subtitle since the \n would mess with opponent's name.

Proposed current_frame: `running_score \ntime_remaining`
Proposed title: subtitle = {current_frame}

Try annotate if current_frame is not well.

And this may be too chunky.

**Comment by imjakedaniels** [comment]
<img width="812" alt="Screen Shot 2019-12-26 at 11 05 38 AM" src="https://user-images.githubusercontent.com/34351878/71482272-b369f280-27cf-11ea-9d79-2dfabefade76.png">

**Comment by imjakedaniels** [comment]
Score is kinda small for my liking. Maybe the title could shrink or flat out be removed as it will be in the reddit title.

Need to add `time = 12:00` to the opening frame to remove an `NA` issue
Need to shed the decimal point .0 since it is constant.
Want to add Q1, Q2, Q3, Q4 before the time.

<img width="1023" alt="Screen Shot 2019-12-26 at 12 20 45 PM" src="https://user-images.githubusercontent.com/34351878/71484393-2ed0a180-27da-11ea-800e-b6d4e6e798ea.png">

**Comment by imjakedaniels** [comment]
Resolved `time = 12:00`, and shed the decimal point.

**Comment by rleonard98** [comment]
Your super clean interface is very attractive.  I had in mind timing of the dropping b-balls matching their relative timing during the game.  So no additional (text) info required on the interface to distract the viewing experience.  Hope I'm making sense.  I have not programmed in years (decades, really) and it is just by fluke that I have a github acct or even know what one is, so don't read too much into my suggestions.  I think it could be pretty tricky i.e. could you start out with the total duration of the the game, calculate the proportional times of the ball drops and control the drops accordingly?

**Comment by imjakedaniels** [comment]
Hey @rleonard98! Cheers for the suggestion btw. I see what you're thinking. So far the only delay during the animation occurs when the opponent scores.

For more insight to you, the current sequence of the animation i created using running_score, so I'm following only scoring plays.
<img width="876" alt="Screen Shot 2019-12-26 at 5 07 20 PM" src="https://user-images.githubusercontent.com/34351878/71492018-458aee80-2802-11ea-9535-63a32703e41e.png">

But if you check the **Time** column on the play-by-play data, I can use misses, rebounds, or turnovers to generate more events in the background that wouldn't change the score, but cause a longer delay between baskets to create more realistic gaps between events, just it wouldn't be "smooth." This could be built into what I currently have.

<img width="968" alt="Screen Shot 2019-12-26 at 5 10 24 PM" src="https://user-images.githubusercontent.com/34351878/71492078-a0244a80-2802-11ea-9bda-d4d3e73de5a4.png">

However, I can certainly generate the full time sequence you're suggesting. But I'm not certain the "bouncing" animation would handle the higher frequency. The package I use is quite basic. But so is my understanding of it.

1. I'm going to try to add the shot misses events into the sequence to let the delay grow in a more realistic way
2. I'll build a full time sequence and see if I can control the animation behaviour.

**Comment by imjakedaniels** [comment]
Also one NASTY thing is free throws since there can be 2 baskets at the same time from the same person. My stuff blows up. But that's why binding the time to the score is really, really good.

**Comment by imjakedaniels** [comment]
Need create a final frame to end on 0:00.
